development:
  clients:
    default:
      uri: mongodb://literallight:Satori71@ds155727.mlab.com:55727/heroku_0zclqwdh
      options:
  options:
     raise_not_found_error: true

test:
  clients:
    default:
      database: myDB
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MLAB_URL'] %>
      options:
