development:
  clients:
    default:
      database: myDB
      hosts:
        - localhost:27017
      options:
  options:
     raise_not_found_error: true

test:
  clients:
    default:
      database: myDB
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
