# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
nominee_list = [
["1953","Hugo","Alfred Bester","The Demolished Man","https://en.wikipedia.org/wiki/The_Demolished_Man"],
["1955","Hugo","Mark Clifton & Frank Riley","They'd Rather Be Right (aka: The Forever Machine)",""],
["1956","Hugo","Robert A. Heinlein","Double Star","https://en.wikipedia.org/wiki/Double_Star"],
["1958","Hugo","Fritz Leiber","The Big Time","https://en.wikipedia.org/wiki/The_Big_Time"],
["1959","","Poul Anderson","We Have Fed Our Sea (aka: The Enemy Stars)",""],
["1959","Hugo","James Blish","A Case of Conscience","https://en.wikipedia.org/wiki/A_Case_of_Conscience"],
["1959","","Robert A. Heinlein","Have Space Suit - Will Travel","https://en.wikipedia.org/wiki/Have_Space_Suit%E2%80%94Will_Travel"],
["1959","","Robert Sheckley","Time Killer (aka: Immortality, Inc.)","https://en.wikipedia.org/wiki/Immortality,_Inc."],
["1959","","Algis Budrys","Who?","https://en.wikipedia.org/wiki/Who%3F_(novel)"],
["1960","","Mark Phillips","That Sweet Little Old Lady (aka: Brain Twister)",""],
["1960","","Gordon R. Dickson","Dorsai! (aka: The Genetic General)","https://en.wikipedia.org/wiki/Dorsai!"],
["1960","Hugo","Robert A. Heinlein","Starship Troopers","https://en.wikipedia.org/wiki/Starship_Troopers"],
["1960","","Murray Leinster","The Pirates of Ersatz (aka: The Pirates of Zan)","https://en.wikipedia.org/wiki/The_Pirates_of_Zan"],
["1960","","Kurt Vonnegut","The Sirens of Titan","https://en.wikipedia.org/wiki/The_Sirens_of_Titan"],
["1961","Hugo","Walter M. Miller, Jr.","A Canticle for Leibowitz","https://en.wikipedia.org/wiki/A_Canticle_for_Leibowitz"],
["1961","","Harry Harrison","Deathworld","https://en.wikipedia.org/wiki/Deathworld"],
["1961","","Algis Budrys","Rogue Moon","https://en.wikipedia.org/wiki/Rogue_Moon"],
["1961","","Poul Anderson","The High Crusade","https://en.wikipedia.org/wiki/The_High_Crusade"],
["1961","","Theodore Sturgeon","Venus Plus X","https://en.wikipedia.org/wiki/Venus_Plus_X"],
["1962","","Clifford D. Simak","The Fisherman (aka: Time Is the Simplest Thing)",""],
["1962","","Daniel F. Galouye","Dark Universe","https://en.wikipedia.org/wiki/Dark_Universe_(novel)"],
["1962","","Harry Harrison","Planet of the Damned (aka: Sense of Obligation)","https://en.wikipedia.org/wiki/Planet_of_the_Damned"],
["1962","","James White","Second Ending","https://en.wikipedia.org/wiki/Second_Ending"],
["1962","Hugo","Robert A. Heinlein","Stranger in a Strange Land","https://en.wikipedia.org/wiki/Stranger_in_a_Strange_Land"],
["1963","","Arthur C. Clarke","A Fall of Moondust",""],
["1963","","Jean Bruller","Sylva",""],
["1963","","H. Beam Piper","Little Fuzzy","https://en.wikipedia.org/wiki/Little_Fuzzy"],
["1963","Hugo","Philip K. Dick","The Man in the High Castle","https://en.wikipedia.org/wiki/The_Man_in_the_High_Castle"],
["1963","","Marion Zimmer Bradley","The Sword of Aldones","https://en.wikipedia.org/wiki/The_Sword_of_Aldones"],
["1964","","Frank Herbert","Dune World",""],
["1964","","Kurt Vonnegut","Cat's Cradle","https://en.wikipedia.org/wiki/Cat%27s_Cradle"],
["1964","","Robert A. Heinlein","Glory Road","https://en.wikipedia.org/wiki/Glory_Road"],
["1964","Hugo","Clifford D. Simak","Here Gather the Stars (aka: Way Station)","https://en.wikipedia.org/wiki/Way_Station_(novel)"],
["1964","","Andre Norton","Witch World","https://en.wikipedia.org/wiki/Witch_World_(novel)"],
["1965","","Edgar Pangborn","Davy","https://en.wikipedia.org/wiki/Davy_(novel)"],
["1965","","Cordwainer Smith","The Planet Buyer (aka: The Boy Who Bought Old Earth)","https://en.wikipedia.org/wiki/Norstrilia"],
["1965","Hugo","Fritz Leiber","The Wanderer","https://en.wikipedia.org/wiki/The_Wanderer_(Leiber_novel)"],
["1965","","John Brunner","The Whole Man","https://en.wikipedia.org/wiki/The_Whole_Man"],
["1966","Hugo","Roger Zelazny","...And Call Me Conrad (aka: This Immortal)",""],
["1966","","Keith Laumer","A Plague of Demons",""],
["1966","","Clifford D. Simak","All Flesh is Grass",""],
["1966","","Avram Davidson","Rogue Dragon",""],
["1966","","Theodore L. Thomas & Kate Wilhelm","The Clone",""],
["1966","","Robert A. Heinlein","The Moon Is a Harsh Mistress",""],
["1966","","G. C. Edmondson","The Ship That Sailed the Time Stream",""],
["1966","","Philip K. Dick","Dr. Bloodmoney, or How We Got Along After the Bomb","https://en.wikipedia.org/wiki/Dr._Bloodmoney,_or_How_We_Got_Along_After_the_Bomb"],
["1966","Hugo,Nebula","Frank Herbert","Dune","https://en.wikipedia.org/wiki/Dune_(novel)"],
["1966","","William S. Burroughs","Nova Express","https://en.wikipedia.org/wiki/Nova_Express"],
["1966","","Edward E. Smith","Skylark DuQuesne","https://en.wikipedia.org/wiki/Skylark_DuQuesne"],
["1966","","James White","The Escape Orbit","https://en.wikipedia.org/wiki/The_Escape_Orbit"],
["1966","","Thomas M. Disch","The Genocides","https://en.wikipedia.org/wiki/The_Genocides"],
["1966","","John Brunner","The Squares of the City","https://en.wikipedia.org/wiki/The_Squares_of_the_City"],
["1966","","Poul Anderson","The Star Fox","https://en.wikipedia.org/wiki/The_Star_Fox"],
["1966","","Philip K. Dick","The Three Stigmata of Palmer Eldritch","https://en.wikipedia.org/wiki/The_Three_Stigmata_of_Palmer_Eldritch"],
["1967","","Thomas Burnett Swann","Day of the Minotaur",""],
["1967","Nebula","Samuel R. Delany","Babel-17","https://en.wikipedia.org/wiki/Babel-17"],
["1967","Nebula","Daniel Keyes","Flowers for Algernon","https://en.wikipedia.org/wiki/Flowers_for_Algernon"],
["1967","Hugo","Robert A. Heinlein","The Moon Is a Harsh Mistress","https://en.wikipedia.org/wiki/The_Moon_Is_a_Harsh_Mistress"],
["1967","","James H. Schmitz","The Witches of Karres","https://en.wikipedia.org/wiki/The_Witches_of_Karres"],
["1967","","Randall Garrett","Too Many Magicians","https://en.wikipedia.org/wiki/Too_Many_Magicians"],
["1968","","Hayden Howard","The Eskimo Invasion",""],
["1968","","Piers Anthony","Chthon","https://en.wikipedia.org/wiki/Chthon_(novel)"],
["1968","Hugo","Roger Zelazny","Lord of Light","https://en.wikipedia.org/wiki/Lord_of_Light"],
["1968","","Chester Anderson","The Butterfly Kid","https://en.wikipedia.org/wiki/The_Butterfly_Kid"],
["1968","Nebula","Samuel R. Delany","The Einstein Intersection","https://en.wikipedia.org/wiki/The_Einstein_Intersection"],
["1968","","Robert Silverberg","Thorns","https://en.wikipedia.org/wiki/Thorns_(novel)"],
["1969","","Joanna Russ","Picnic on Paradise",""],
["1969","","James Blish","Black Easter","https://en.wikipedia.org/wiki/Black_Easter"],
["1969","","Philip K. Dick","Do Androids Dream of Electric Sheep?","https://en.wikipedia.org/wiki/Do_Androids_Dream_of_Electric_Sheep%3F"],
["1969","","Samuel R. Delany","Nova","https://en.wikipedia.org/wiki/Nova_(novel)"],
["1969","","R. A. Lafferty","Past Master","https://en.wikipedia.org/wiki/Past_Master_(novel)"],
["1969","Nebula","Alexei Panshin","Rite of Passage","https://en.wikipedia.org/wiki/Rite_of_Passage_(novel)"],
["1969","Hugo","John Brunner","Stand on Zanzibar","https://en.wikipedia.org/wiki/Stand_on_Zanzibar"],
["1969","","Clifford D. Simak","The Goblin Reservation","https://en.wikipedia.org/wiki/The_Goblin_Reservation"],
["1969","","Robert Silverberg","The Masks of Time","https://en.wikipedia.org/wiki/The_Masks_of_Time"],
["1970","","Norman Spinrad","Bug Jack Barron","https://en.wikipedia.org/wiki/Bug_Jack_Barron"],
["1970","","Roger Zelazny","Isle of the Dead","https://en.wikipedia.org/wiki/Isle_of_the_Dead_(Zelazny_novel)"],
["1970","","Piers Anthony","Macroscope","https://en.wikipedia.org/wiki/Macroscope_(novel)"],
["1970","","Kurt Vonnegut","Slaughterhouse-Five","https://en.wikipedia.org/wiki/Slaughterhouse-Five"],
["1970","","John Brunner","The Jagged Orbit","https://en.wikipedia.org/wiki/The_Jagged_Orbit"],
["1970","Hugo,Nebula","Ursula K. Le Guin","The Left Hand of Darkness","https://en.wikipedia.org/wiki/The_Left_Hand_of_Darkness"],
["1970","","Robert Silverberg","Up the Line","https://en.wikipedia.org/wiki/Up_the_Line"],
["1971","","David G. Compton","The Steel Crocodile",""],
["1971","","Joanna Russ","And Chaos Died","https://en.wikipedia.org/wiki/And_Chaos_Died"],
["1971","","R. A. Lafferty","Fourth Mansions","https://en.wikipedia.org/wiki/Fourth_Mansions"],
["1971","Hugo,Nebula","Larry Niven","Ringworld","https://en.wikipedia.org/wiki/Ringworld"],
["1971","","Hal Clement","Star Light","https://en.wikipedia.org/wiki/Star_Light"],
["1971","","Poul Anderson","Tau Zero","https://en.wikipedia.org/wiki/Tau_Zero"],
["1971","","Wilson Tucker","The Year of the Quiet Sun","https://en.wikipedia.org/wiki/The_Year_of_the_Quiet_Sun"],
["1971","","Robert Silverberg","Tower of Glass","https://en.wikipedia.org/wiki/Tower_of_Glass"],
["1972","Nebula","Robert Silverberg","A Time of Changes",""],
["1972","","Kate Wilhelm","Margaret and I",""],
["1972","","Poul Anderson","The Byworlder",""],
["1972","","R. A. Lafferty","The Devil is Dead",""],
["1972","","Anne McCaffrey","Dragonquest","https://en.wikipedia.org/wiki/Dragonquest"],
["1972","","T. J. Bass","Half Past Human","https://en.wikipedia.org/wiki/Half_Past_Human"],
["1972","","Roger Zelazny","Jack of Shadows","https://en.wikipedia.org/wiki/Jack_of_Shadows"],
["1972","","Ursula K. Le Guin","The Lathe of Heaven","https://en.wikipedia.org/wiki/The_Lathe_of_Heaven"],
["1972","Hugo","Philip Jos‚ Farmer","To Your Scattered Bodies Go","https://en.wikipedia.org/wiki/To_Your_Scattered_Bodies_Go"],
["1973","","Clifford D. Simak","A Choice of Gods",""],
["1973","","George Alec Effinger","What Entropy Means to Me",""],
["1973","","Robert Silverberg","Dying Inside","https://en.wikipedia.org/wiki/Dying_Inside"],
["1973","","Robert Silverberg","The Book of Skulls","https://en.wikipedia.org/wiki/The_Book_of_Skulls"],
["1973","Hugo,Nebula","Isaac Asimov","The Gods Themselves","https://en.wikipedia.org/wiki/The_Gods_Themselves"],
["1973","","Norman Spinrad","The Iron Dream","https://en.wikipedia.org/wiki/The_Iron_Dream"],
["1973","","John Brunner","The Sheep Look Up","https://en.wikipedia.org/wiki/The_Sheep_Look_Up"],
["1973","","Poul Anderson","There Will Be Time","https://en.wikipedia.org/wiki/There_Will_Be_Time"],
["1973","","David Gerrold","When HARLIE Was One","https://en.wikipedia.org/wiki/When_HARLIE_Was_One"],
["1974","","Poul Anderson","The People of the Wind",""],
["1974","","Thomas Pynchon","Gravity's Rainbow","https://en.wikipedia.org/wiki/Gravity%27s_Rainbow"],
["1974","","Larry Niven","Protector","https://en.wikipedia.org/wiki/Protector_(novel)"],
["1974","Hugo,Nebula","Arthur C. Clarke","Rendezvous with Rama","https://en.wikipedia.org/wiki/Rendezvous_with_Rama"],
["1974","","David Gerrold","The Man Who Folded Himself","https://en.wikipedia.org/wiki/The_Man_Who_Folded_Himself"],
["1974","","Robert A. Heinlein","Time Enough for Love","https://en.wikipedia.org/wiki/Time_Enough_for_Love"],
["1975","","Thomas M. Disch","334","https://en.wikipedia.org/wiki/334_(novel)"],
["1975","","Poul Anderson","Fire Time","https://en.wikipedia.org/wiki/Fire_Time"],
["1975","","Philip K. Dick","Flow My Tears, the Policeman Said","https://en.wikipedia.org/wiki/Flow_My_Tears,_the_Policeman_Said"],
["1975","","Christopher Priest","Inverted World","https://en.wikipedia.org/wiki/Inverted_World"],
["1975","Hugo,Nebula","Ursula K. Le Guin","The Dispossessed","https://en.wikipedia.org/wiki/The_Dispossessed"],
["1975","","T. J. Bass","The Godwhale","https://en.wikipedia.org/wiki/The_Godwhale"],
["1975","","Larry Niven","The Mote in God's Eye","https://en.wikipedia.org/wiki/The_Mote_in_God%27s_Eye"],
["1976","","Michael Bishop","A Funeral for the Eyes of Fire",""],
["1976","","Arthur Byron Cover","Autumn Angels",""],
["1976","","Barry N. Malzberg","Guernica Night",""],
["1976","","Ian Watson","The Embedding",""],
["1976","","Vonda N. McIntyre","The Exile Waiting",""],
["1976","","Katherine MacLean","The Missing Man",""],
["1976","","Robert Silverberg","The Stochastic Man",""],
["1976","","Poul Anderson","A Midsummer Tempest","https://en.wikipedia.org/wiki/A_Midsummer_Tempest"],
["1976","","Samuel R. Delany","Dhalgren","https://en.wikipedia.org/wiki/Dhalgren"],
["1976","","Roger Zelazny","Doorways in the Sand","https://en.wikipedia.org/wiki/Doorways_in_the_Sand"],
["1976","","Larry Niven & Jerry Pournelle","Inferno","https://en.wikipedia.org/wiki/Inferno_(Niven_and_Pournelle_novel)"],
["1976","","Italo Calvino","Invisible Cities","https://en.wikipedia.org/wiki/Invisible_Cities"],
["1976","","E. L. Doctorow","Ragtime","https://en.wikipedia.org/wiki/Ragtime_(novel)"],
["1976","","Tanith Lee","The Birthgrave","https://en.wikipedia.org/wiki/The_Birthgrave_Trilogy"],
["1976","","Alfred Bester","The Computer Connection (aka: The Indian Giver)","https://en.wikipedia.org/wiki/The_Computer_Connection"],
["1976","","Joanna Russ","The Female Man","https://en.wikipedia.org/wiki/The_Female_Man"],
["1976","Hugo,Nebula","Joe Haldeman","The Forever War","https://en.wikipedia.org/wiki/The_Forever_War"],
["1976","","Marion Zimmer Bradley","The Heritage of Hastur","https://en.wikipedia.org/wiki/The_Heritage_of_Hastur"],
["1976","","Larry Niven","The Mote in God's Eye","https://en.wikipedia.org/wiki/The_Mote_in_God%27s_Eye"],
["1977","","Marta Randall","Islands",""],
["1977","","Joe Haldeman","Mindbridge",""],
["1977","","Frank Herbert","Children of Dune","https://en.wikipedia.org/wiki/Children_of_Dune"],
["1977","","Larry Niven & Jerry Pournelle","Inferno","https://en.wikipedia.org/wiki/Inferno_(Niven_and_Pournelle_novel)"],
["1977","Nebula","Frederik Pohl","Man Plus","https://en.wikipedia.org/wiki/Man_Plus"],
["1977","","Frederik Pohl","Man Plus","https://en.wikipedia.org/wiki/Man_Plus"],
["1977","","Robert Silverberg","Shadrach in the Furnace","https://en.wikipedia.org/wiki/Shadrach_in_the_Furnace"],
["1977","","Samuel R. Delany","Triton","https://en.wikipedia.org/wiki/Triton_(novel)"],
["1977","Hugo","Kate Wilhelm","Where Late the Sweet Birds Sang","https://en.wikipedia.org/wiki/Where_Late_the_Sweet_Birds_Sang"],
["1977","","Kate Wilhelm","Where Late the Sweet Birds Sang","https://en.wikipedia.org/wiki/Where_Late_the_Sweet_Birds_Sang"],
["1978","","Terry Carr","Cirque",""],
["1978","","David Gerrold","Moonstar Odyssey",""],
["1978","","Richard A. Lupoff","Sword of Demon",""],
["1978","","Gordon R. Dickson","Time Storm",""],
["1978","","George R. R. Martin","Dying of the Light","https://en.wikipedia.org/wiki/Dying_of_the_Light"],
["1978","Hugo,Nebula","Frederik Pohl","Gateway","https://en.wikipedia.org/wiki/Gateway_(novel)"],
["1978","","Gregory Benford","In the Ocean of Night","https://en.wikipedia.org/wiki/In_the_Ocean_of_Night"],
["1978","","Larry Niven & Jerry Pournelle","Lucifer's Hammer","https://en.wikipedia.org/wiki/Lucifer%27s_Hammer"],
["1978","","Marion Zimmer Bradley","The Forbidden Tower","https://en.wikipedia.org/wiki/The_Forbidden_Tower"],
["1979","","Tom Reamy","Blind Voices",""],
["1979","Hugo,Nebula","Vonda N. McIntyre","Dreamsnake","https://en.wikipedia.org/wiki/Dreamsnake"],
["1979","","C. J. Cherryh","The Faded Sun: Kesrith","https://en.wikipedia.org/wiki/Faded_Sun_Trilogy"],
["1979","","Gore Vidal","Kalki","https://en.wikipedia.org/wiki/Kalki_(novel)"],
["1979","","Gardner Dozois","Strangers","https://en.wikipedia.org/wiki/Strangers_(Gardner_Dozois_novel)"],
["1979","","Anne McCaffrey","The White Dragon","https://en.wikipedia.org/wiki/The_White_Dragon_(novel)"],
["1980","","Frederik Pohl","Jem",""],
["1980","","Kate Wilhelm","Juniper Time",""],
["1980","","Richard Cowper","The Road to Corlay",""],
["1980","","Patricia A. McKillip","Harpist in the Wind","https://en.wikipedia.org/wiki/Harpist_in_the_Wind"],
["1980","","Thomas Disch","On Wings of Song","https://en.wikipedia.org/wiki/On_Wings_of_Song"],
["1980","Hugo,Nebula","Arthur C. Clarke","The Fountains of Paradise","https://en.wikipedia.org/wiki/The_Fountains_of_Paradise"],
["1980","","John Varley","Titan","https://en.wikipedia.org/wiki/Titan_(John_Varley_novel)"],
["1981","","Robert Stallman","The Orphan",""],
["1981","","Frederik Pohl","Beyond the Blue Event Horizon","https://en.wikipedia.org/wiki/Beyond_the_Blue_Event_Horizon"],
["1981","","Robert Silverberg","Lord Valentine's Castle","https://en.wikipedia.org/wiki/Majipoor_series"],
["1981","","Walter Tevis","Mockingbird","https://en.wikipedia.org/wiki/Mockingbird_(Tevis_novel)"],
["1981","","Larry Niven","The Ringworld Engineers","https://en.wikipedia.org/wiki/The_Ringworld_Engineers"],
["1981","","Gene Wolfe","The Shadow of the Torturer","https://en.wikipedia.org/wiki/The_Shadow_of_the_Torturer"],
["1981","Hugo","Joan D. Vinge","The Snow Queen","https://en.wikipedia.org/wiki/The_Snow_Queen_(Vinge_novel)"],
["1981","","Joan D. Vinge","The Snow Queen","https://en.wikipedia.org/wiki/The_Snow_Queen_(Vinge_novel)"],
["1981","Nebula","Gregory Benford","Timescape","https://en.wikipedia.org/wiki/Timescape"],
["1981","","John Varley","Wizard","https://en.wikipedia.org/wiki/Wizard_(novel)"],
["1982","","Clifford D. Simak","Project Pope",""],
["1982","","Suzy McKee Charnas","The Vampire Tapestry",""],
["1982","Hugo","C. J. Cherryh","Downbelow Station","https://en.wikipedia.org/wiki/Downbelow_Station"],
["1982","","John Crowley","Little, Big","https://en.wikipedia.org/wiki/Little,_Big"],
["1982","","A. A. Attanasio","Radix","https://en.wikipedia.org/wiki/Radix_(novel)"],
["1982","","Russell Hoban","Riddley Walker","https://en.wikipedia.org/wiki/Riddley_Walker"],
["1982","Nebula","Gene Wolfe","The Claw of the Conciliator","https://en.wikipedia.org/wiki/The_Claw_of_the_Conciliator"],
["1982","","Gene Wolfe","The Claw of the Conciliator","https://en.wikipedia.org/wiki/The_Claw_of_the_Conciliator"],
["1982","","Julian May","The Many-Colored Land","https://en.wikipedia.org/wiki/The_Many-Colored_Land"],
["1983","","Arthur C. Clarke","2010: Odyssey Two","https://en.wikipedia.org/wiki/2010:_Odyssey_Two"],
["1983","","Donald Kingsbury","Courtship Rite","https://en.wikipedia.org/wiki/Courtship_Rite"],
["1983","Hugo","Isaac Asimov","Foundation's Edge","https://en.wikipedia.org/wiki/Foundation%27s_Edge"],
["1983","","Isaac Asimov","Foundation's Edge","https://en.wikipedia.org/wiki/Foundation%27s_Edge"],
["1983","","Robert A. Heinlein","Friday","https://en.wikipedia.org/wiki/Friday_(novel)"],
["1983","","Brian Aldiss","Helliconia Spring","https://en.wikipedia.org/wiki/Helliconia"],
["1983","Nebula","Michael Bishop","No Enemy But Time","https://en.wikipedia.org/wiki/No_Enemy_But_Time"],
["1983","","C. J. Cherryh","The Pride of Chanur","https://en.wikipedia.org/wiki/The_Chanur_novels"],
["1983","","Gene Wolfe","The Sword of the Lictor","https://en.wikipedia.org/wiki/The_Sword_of_the_Lictor"],
["1983","","Philip K. Dick","The Transmigration of Timothy Archer","https://en.wikipedia.org/wiki/The_Transmigration_of_Timothy_Archer"],
["1984","","Gregory Benford","Against Infinity",""],
["1984","","Norman Spinrad","The Void Captain's Tale",""],
["1984","","Jack Vance","Lyonesse","https://en.wikipedia.org/wiki/Lyonesse_Trilogy"],
["1984","","John Varley","Millennium","https://en.wikipedia.org/wiki/Millennium_(novel)"],
["1984","","Anne McCaffrey","Moreta: Dragonlady of Pern","https://en.wikipedia.org/wiki/Moreta:_Dragonlady_of_Pern"],
["1984","Hugo,Nebula","David Brin","Startide Rising","https://en.wikipedia.org/wiki/Startide_Rising"],
["1984","","R. A. MacAvoy","Tea with the Black Dragon","https://en.wikipedia.org/wiki/Tea_with_the_Black_Dragon"],
["1984","","Gene Wolfe","The Citadel of the Autarch","https://en.wikipedia.org/wiki/The_Book_of_the_New_Sun"],
["1984","","Isaac Asimov","The Robots of Dawn","https://en.wikipedia.org/wiki/The_Robots_of_Dawn"],
["1985","","Lewis Shiner","Frontera",""],
["1985","","Jack Dann","The Man Who Melted",""],
["1985","","David R. Palmer","Emergence","https://en.wikipedia.org/wiki/Emergence_(novel)"],
["1985","","Robert A. Heinlein","Job: A Comedy of Justice","https://en.wikipedia.org/wiki/Job:_A_Comedy_of_Justice"],
["1985","Hugo,Nebula","William Gibson","Neuromancer","https://en.wikipedia.org/wiki/Neuromancer"],
["1985","","Larry Niven","The Integral Trees","https://en.wikipedia.org/wiki/The_Integral_Trees"],
["1985","","Vernor Vinge","The Peace War","https://en.wikipedia.org/wiki/The_Peace_War"],
["1985","","Kim Stanley Robinson","The Wild Shore","https://en.wikipedia.org/wiki/Three_Californias_Trilogy"],
["1986","","Tim Powers","Dinner at Deviant's Palace",""],
["1986","","Barry N. Malzberg","The Remaking of Sigmund Freud",""],
["1986","","Greg Bear","Blood Music","https://en.wikipedia.org/wiki/Blood_Music_(novel)"],
["1986","","C. J. Cherryh","Cuckoo's Egg","https://en.wikipedia.org/wiki/Cuckoo%27s_Egg"],
["1986","Hugo,Nebula","Orson Scott Card","Ender's Game","https://en.wikipedia.org/wiki/Ender%27s_Game"],
["1986","","Larry Niven & Jerry Pournelle","Footfall","https://en.wikipedia.org/wiki/Footfall"],
["1986","","Brian Aldiss","Helliconia Winter","https://en.wikipedia.org/wiki/Helliconia"],
["1986","","Bruce Sterling","Schismatrix","https://en.wikipedia.org/wiki/Schismatrix"],
["1986","","David Brin","The Postman","https://en.wikipedia.org/wiki/The_Postman"],
["1987","","Leigh Kennedy","The Journal of Nicholas the American",""],
["1987","","James K. Morrow","This is the Way the World Ends",""],
["1987","","William Gibson","Count Zero","https://en.wikipedia.org/wiki/Count_Zero"],
["1987","","Gene Wolfe","Free Live Free","https://en.wikipedia.org/wiki/Free_Live_Free"],
["1987","","Bob Shaw","The Ragged Astronauts","https://en.wikipedia.org/wiki/Land_and_Overland"],
["1987","","Vernor Vinge","Marooned in Realtime","https://en.wikipedia.org/wiki/Marooned_in_Realtime"],
["1987","","L. Ron Hubbard","Black Genesis","https://en.wikipedia.org/wiki/Mission_Earth_(novel)"],
["1987","Hugo,Nebula","Orson Scott Card","Speaker for the Dead","https://en.wikipedia.org/wiki/Speaker_for_the_Dead"],
["1987","","Margaret Atwood","The Handmaid's Tale","https://en.wikipedia.org/wiki/The_Handmaid%27s_Tale"],
["1988","","Avram Davidson","Vergil in Averno",""],
["1988","","Lewis Shiner","Deserted Cities of the Heart",""],
["1988","","George Turner","Drowning Towers",""],
["1988","Hugo","C. J. Cherryh","Cyteen","https://en.wikipedia.org/wiki/Cyteen"],
["1988","Nebula","Lois McMaster Bujold","Falling Free","https://en.wikipedia.org/wiki/Falling_Free"],
["1988","","Lois McMaster Bujold","Falling Free","https://en.wikipedia.org/wiki/Falling_Free"],
["1988","","Gregory Benford","Great Sky River","https://en.wikipedia.org/wiki/Great_Sky_River_(novel)"],
["1988","","Bruce Sterling","Islands in the Net","https://en.wikipedia.org/wiki/Islands_in_the_Net"],
["1988","","William Gibson","Mona Lisa Overdrive","https://en.wikipedia.org/wiki/Mona_Lisa_Overdrive"],
["1988","","Orson Scott Card","Red Prophet","https://en.wikipedia.org/wiki/Red_Prophet"],
["1988","","Orson Scott Card","Seventh Son","https://en.wikipedia.org/wiki/Seventh_Son_(novel)"],
["1988","","Gene Wolfe","Soldier of the Mist","https://en.wikipedia.org/wiki/Soldier_of_the_Mist"],
["1988","Nebula","Pat Murphy","The Falling Woman","https://en.wikipedia.org/wiki/The_Falling_Woman"],
["1988","","Greg Bear","The Forge of God","https://en.wikipedia.org/wiki/The_Forge_of_God"],
["1988","Hugo","David Brin","The Uplift War","https://en.wikipedia.org/wiki/The_Uplift_War"],
["1988","","David Brin","The Uplift War","https://en.wikipedia.org/wiki/The_Uplift_War"],
["1988","","Gene Wolfe","The Urth of the New Sun","https://en.wikipedia.org/wiki/The_Urth_of_the_New_Sun"],
["1988","","Gene Wolfe","The Urth of the New Sun","https://en.wikipedia.org/wiki/The_Urth_of_the_New_Sun"],
["1988","","George Alec Effinger","When Gravity Fails","https://en.wikipedia.org/wiki/When_Gravity_Fails"],
["1990","","John Kessel","Good News From Outer Space",""],
["1990","","Mike Resnick","Ivory: A Legend of Past and Future",""],
["1990","","Jane Yolen","Sister Light, Sister Dark",""],
["1990","","George Alec Effinger","A Fire in the Sun","https://en.wikipedia.org/wiki/A_Fire_in_the_Sun"],
["1990","","Sheri S. Tepper","Grass","https://en.wikipedia.org/wiki/Grass_(novel)"],
["1990","Hugo","Dan Simmons","Hyperion","https://en.wikipedia.org/wiki/Hyperion_(Simmons_novel)"],
["1990","","Orson Scott Card","Prentice Alvin","https://en.wikipedia.org/wiki/Prentice_Alvin"],
["1990","","Poul Anderson","The Boat of a Million Years","https://en.wikipedia.org/wiki/The_Boat_of_a_Million_Years"],
["1990","Nebula","Elizabeth Ann Scarborough","The Healer's War","https://en.wikipedia.org/wiki/The_Healer%27s_War"],
["1991","","John E. Stith","Redshift Rendezvous",""],
["1991","","Michael P. Kube-McDowell","The Quiet Pools",""],
["1991","","Jane Yolen","White Jenna",""],
["1991","","David Brin","Earth","https://en.wikipedia.org/wiki/Earth_(Brin_novel)"],
["1991","","Valerie Martin","Mary Reilly","https://en.wikipedia.org/wiki/Mary_Reilly_(novel)"],
["1991","","James K. Morrow","Only Begotten Daughter","https://en.wikipedia.org/wiki/Only_Begotten_Daughter"],
["1991","","Greg Bear","Queen of Angels","https://en.wikipedia.org/wiki/Queen_of_Angels_(novel)"],
["1991","Nebula","Ursula K. Le Guin","Tehanu: The Last Book of Earthsea","https://en.wikipedia.org/wiki/Tehanu"],
["1991","","Dan Simmons","The Fall of Hyperion","https://en.wikipedia.org/wiki/The_Fall_of_Hyperion_(novel)"],
["1991","Hugo","Lois McMaster Bujold","The Vor Game","https://en.wikipedia.org/wiki/The_Vor_Game"],
["1992","","Pat Cadigan","Synners",""],
["1992","","Joan D. Vinge","The Summer Queen",""],
["1992","","Anne McCaffrey","All the Weyrs of Pern","https://en.wikipedia.org/wiki/All_the_Weyrs_of_Pern"],
["1992","Hugo","Lois McMaster Bujold","Barrayar","https://en.wikipedia.org/wiki/Barrayar"],
["1992","","Emma Bull","Bone Dance","https://en.wikipedia.org/wiki/Bone_Dance"],
["1992","","John Barnes","Orbital Resonance","https://en.wikipedia.org/wiki/Orbital_Resonance_(novel)"],
["1992","Nebula","Michael Swanwick","Stations of the Tide","https://en.wikipedia.org/wiki/Stations_of_the_Tide"],
["1992","","Michael Swanwick","Stations of the Tide","https://en.wikipedia.org/wiki/Stations_of_the_Tide"],
["1992","","Bruce Sterling &William Gibson","The Difference Engine","https://en.wikipedia.org/wiki/The_Difference_Engine"],
["1992","","Lois McMaster Bujold","Barrayar","https://en.wikipedia.org/wiki/Vorkosigan_Saga"],
["1992","","Orson Scott Card","Xenocide","https://en.wikipedia.org/wiki/Xenocide"],
["1993","","Karen Joy Fowler","Sarah Canary",""],
["1993","Hugo","Vernor Vinge","A Fire Upon the Deep","https://en.wikipedia.org/wiki/A_Fire_Upon_the_Deep"],
["1993","","Vernor Vinge","A Fire Upon the Deep","https://en.wikipedia.org/wiki/A_Fire_Upon_the_Deep"],
["1993","","John Barnes","A Million Open Doors","https://en.wikipedia.org/wiki/A_Million_Open_Doors"],
["1993","","Jane Yolen","Briar Rose","https://en.wikipedia.org/wiki/Briar_Rose_(novel)"],
["1993","","Maureen F. McHugh","China Mountain Zhang","https://en.wikipedia.org/wiki/China_Mountain_Zhang"],
["1993","Hugo,Nebula","Connie Willis","Doomsday Book","https://en.wikipedia.org/wiki/Doomsday_Book_(novel)"],
["1993","","Kim Stanley Robinson","Red Mars","https://en.wikipedia.org/wiki/Mars_trilogy"],
["1993","","John Varley","Steel Beach","https://en.wikipedia.org/wiki/Steel_Beach"],
["1994","","Algis Budrys","Hard Landing",""],
["1994","","Kevin J. Anderson & Doug Beason","Assemblers of Infinity","https://en.wikipedia.org/wiki/Assemblers_of_Infinity"],
["1994","","Nancy Kress","Beggars in Spain","https://en.wikipedia.org/wiki/Beggars_in_Spain"],
["1994","","David Brin","Glory Season","https://en.wikipedia.org/wiki/Glory_Season"],
["1994","Hugo","Kim Stanley Robinson","Green Mars","https://en.wikipedia.org/wiki/Mars_trilogy"],
["1994","Nebula","Kim Stanley Robinson","Red Mars","https://en.wikipedia.org/wiki/Mars_trilogy"],
["1994","","Greg Bear","Moving Mars","https://en.wikipedia.org/wiki/Moving_Mars"],
["1994","","Gene Wolfe","Nightside the Long Sun","https://en.wikipedia.org/wiki/The_Book_of_the_Long_Sun"],
["1994","","William Gibson","Virtual Light","https://en.wikipedia.org/wiki/Virtual_Light"],
["1995","","Michael Bishop","Brittle Innings",""],
["1995","","Rachel Pollack","Temporary Agency",""],
["1995","","George R. R. Martin","A Game of Thrones","https://en.wikipedia.org/wiki/A_Game_of_Thrones"],
["1995","","Roger Zelazny","A Night in the Lonesome October","https://en.wikipedia.org/wiki/A_Night_in_the_Lonesome_October"],
["1995","","Jack McDevitt","Ancient Shores","https://en.wikipedia.org/wiki/Ancient_Shores"],
["1995","","Nancy Kress","Beggars and Choosers","https://en.wikipedia.org/wiki/Beggars_and_Choosers_(novel)"],
["1995","","Connie Willis","Bellwether","https://en.wikipedia.org/wiki/Bellwether_(novel)"],
["1995","","Walter Jon Williams","City on Fire","https://en.wikipedia.org/wiki/City_on_Fire_(novel)"],
["1995","","Kate Elliott","King's Dragon","https://en.wikipedia.org/wiki/Crown_of_Stars_(series)"],
["1995","","Jonathan Lethem","Gun, with Occasional Music","https://en.wikipedia.org/wiki/Gun,_with_Occasional_Music"],
["1995","","Kim Stanley Robinson","Green Mars","https://en.wikipedia.org/wiki/Mars_trilogy"],
["1995","Hugo","Lois McMaster Bujold","Mirror Dance","https://en.wikipedia.org/wiki/Mirror_Dance"],
["1995","","John Barnes","Mother of Storms","https://en.wikipedia.org/wiki/Mother_of_Storms"],
["1995","Nebula","Greg Bear","Moving Mars","https://en.wikipedia.org/wiki/Moving_Mars"],
["1995","","Octavia E. Butler","Parable of the Sower","https://en.wikipedia.org/wiki/Parable_of_the_Sower_(novel)"],
["1995","Nebula","Vonda N. McIntyre","The Moon and the Sun","https://en.wikipedia.org/wiki/The_Moon_and_the_Sun"],
["1995","","James K. Morrow","Towing Jehovah","https://en.wikipedia.org/wiki/Towing_Jehovah"],
["1995","","Lois McMaster Bujold","Memory","https://en.wikipedia.org/wiki/Vorkosigan_Saga"],
["1996","","Paul Park","Celestis",""],
["1996","","Nancy Kress","Beggars and Choosers","https://en.wikipedia.org/wiki/Beggars_and_Choosers_(novel)"],
["1996","","David Brin","Brightness Reef","https://en.wikipedia.org/wiki/Brightness_Reef"],
["1996","","Walter Jon Williams","Metropolitan","https://en.wikipedia.org/wiki/Metropolitan_(novel)"],
["1996","","John Barnes","Mother of Storms","https://en.wikipedia.org/wiki/Mother_of_Storms"],
["1996","","Connie Willis","Remake","https://en.wikipedia.org/wiki/Remake_(novel)"],
["1996","","Gene Wolfe","Calde of the Long Sun","https://en.wikipedia.org/wiki/The_Book_of_the_Long_Sun"],
["1996","Hugo","Neal Stephenson","The Diamond Age","https://en.wikipedia.org/wiki/The_Diamond_Age"],
["1996","Nebula","Robert J. Sawyer","The Terminal Experiment","https://en.wikipedia.org/wiki/The_Terminal_Experiment"],
["1996","","Robert J. Sawyer","The Terminal Experiment (aka: Hobson's Choice)","https://en.wikipedia.org/wiki/The_Terminal_Experiment"],
["1996","","Stephen Baxter","The Time Ships","https://en.wikipedia.org/wiki/The_Time_Ships"],
["1997","","Robert J. Sawyer","Starplex",""],
["1997","","Nina Kiriki Hoffman","The Silent Strength of Stones",""],
["1997","","Tim Powers","Expiration Date","https://en.wikipedia.org/wiki/Expiration_Date_(novel)"],
["1997","","Bruce Sterling","Holy Fire","https://en.wikipedia.org/wiki/Holy_Fire_(novel)"],
["1997","Hugo","Kim Stanley Robinson","Blue Mars","https://en.wikipedia.org/wiki/Mars_trilogy"],
["1997","","Lois McMaster Bujold","Memory","https://en.wikipedia.org/wiki/Memory_(Bujold_novel)"],
["1997","","Elizabeth Moon","Remnant Population","https://en.wikipedia.org/wiki/Remnant_Population"],
["1997","Nebula","Nicola Griffith","Slow River","https://en.wikipedia.org/wiki/Slow_River"],
["1997","","Neal Stephenson","The Diamond Age","https://en.wikipedia.org/wiki/The_Diamond_Age"],
["1997","","Patricia A. McKillip","Winter Rose","https://en.wikipedia.org/wiki/Winter_Rose_(novel)"],
["1998","","Robert J. Sawyer","Frameshift",""],
["1998","","Walter Jon Williams","City on Fire","https://en.wikipedia.org/wiki/City_on_Fire_(novel)"],
["1998","Hugo","Joe Haldeman","Forever Peace","https://en.wikipedia.org/wiki/Forever_Peace"],
["1998","","Michael Swanwick","Jack Faust","https://en.wikipedia.org/wiki/Jack_Faust_(novel)"],
["1998","","Dan Simmons","The Rise of Endymion","https://en.wikipedia.org/wiki/The_Rise_of_Endymion"],
["1999","","Martha Wells","Death of the Necromancer",""],
["1999","","Bruce Sterling","Distraction",""],
["1999","","Robert J. Sawyer","Factoring Humanity",""],
["1999","","Jack McDevitt","Moonfall",""],
["1999","","Mary Doria Russell","Children of God","https://en.wikipedia.org/wiki/Children_of_God_(novel)"],
["1999","","Robert Charles Wilson","Darwinia","https://en.wikipedia.org/wiki/Darwinia_(novel)"],
["1999","Nebula","Joe Haldeman","Forever Peace","https://en.wikipedia.org/wiki/Forever_Peace"],
["1999","","Harry Turtledove","How Few Remain","https://en.wikipedia.org/wiki/How_Few_Remain"],
["1999","","Catherine Asaro","The Last Hawk","https://en.wikipedia.org/wiki/The_Last_Hawk"],
["1999","Hugo","Connie Willis","To Say Nothing of the Dog","https://en.wikipedia.org/wiki/To_Say_Nothing_of_the_Dog"],
["1999","","Connie Willis","To Say Nothing of the Dog","https://en.wikipedia.org/wiki/To_Say_Nothing_of_the_Dog"],
["2000","","Maureen F. McHugh","Mission Child",""],
["2000","","Sean Stewart","Mockingbird",""],
["2000","","Ken MacLeod","The Cassini Division",""],
["2000","","Lois McMaster Bujold","A Civil Campaign","https://en.wikipedia.org/wiki/A_Civil_Campaign"],
["2000","","George R. R. Martin","A Clash of Kings","https://en.wikipedia.org/wiki/A_Clash_of_Kings"],
["2000","Hugo","Vernor Vinge","A Deepness in the Sky","https://en.wikipedia.org/wiki/A_Deepness_in_the_Sky"],
["2000","","Vernor Vinge","A Deepness in the Sky","https://en.wikipedia.org/wiki/A_Deepness_in_the_Sky"],
["2000","","Neal Stephenson","Cryptonomicon","https://en.wikipedia.org/wiki/Cryptonomicon"],
["2000","","Greg Bear","Darwin's Radio","https://en.wikipedia.org/wiki/Darwin%27s_Radio"],
["2000","","J. K. Rowling","Harry Potter and the Prisoner of Azkaban","https://en.wikipedia.org/wiki/Harry_Potter_and_the_Prisoner_of_Azkaban"],
["2000","Nebula","Octavia E. Butler","Parable of the Talents","https://en.wikipedia.org/wiki/Parable_of_the_Talents_(novel)"],
["2001","","Kathleen Ann Goonan","Crescent City Rhapsody",""],
["2001","","Charles de Lint","Forests of the Heart",""],
["2001","","Ken MacLeod","The Sky Road",""],
["2001","","George R. R. Martin","A Storm of Swords","https://en.wikipedia.org/wiki/A_Storm_of_Swords"],
["2001","","Robert J. Sawyer","Calculating God","https://en.wikipedia.org/wiki/Calculating_God"],
["2001","Nebula","Greg Bear","Darwin's Radio","https://en.wikipedia.org/wiki/Darwin%27s_Radio"],
["2001","Hugo","J. K. Rowling","Harry Potter and the Goblet of Fire","https://en.wikipedia.org/wiki/Harry_Potter_and_the_Goblet_of_Fire"],
["2001","","Jack McDevitt","Infinity Beach","https://en.wikipedia.org/wiki/Infinity_Beach"],
["2001","","Nalo Hopkinson","Midnight Robber","https://en.wikipedia.org/wiki/Midnight_Robber"],
["2001","","Lois McMaster Bujold","A Civil Campaign","https://en.wikipedia.org/wiki/Vorkosigan_Saga"],
["2002","","Jeffrey Carver","Eternity's End",""],
["2002","","George R. R. Martin","A Storm of Swords","https://en.wikipedia.org/wiki/A_Storm_of_Swords"],
["2002","Hugo","Neil Gaiman","American Gods","https://en.wikipedia.org/wiki/American_Gods"],
["2002","","Ken MacLeod","Cosmonaut Keep","https://en.wikipedia.org/wiki/Cosmonaut_Keep"],
["2002","","Tim Powers","Declare","https://en.wikipedia.org/wiki/Declare"],
["2002","","Geoffrey A. Landis","Mars Crossing","https://en.wikipedia.org/wiki/Mars_Crossing"],
["2002","","Connie Willis","Passage","https://en.wikipedia.org/wiki/Passage_(Willis_novel)"],
["2002","","China Mi‚ville","Perdido Street Station","https://en.wikipedia.org/wiki/Perdido_Street_Station"],
["2002","","Robert Charles Wilson","The Chronoliths","https://en.wikipedia.org/wiki/The_Chronoliths"],
["2002","","Wil McCarthy","The Collapsium","https://en.wikipedia.org/wiki/The_Collapsium"],
["2002","","Lois McMaster Bujold","The Curse of Chalion","https://en.wikipedia.org/wiki/The_Curse_of_Chalion"],
["2002","Nebula","Catherine Asaro","The Quantum Rose","https://en.wikipedia.org/wiki/The_Quantum_Rose"],
["2002","","Patricia A. McKillip","The Tower at Stony Wood","https://en.wikipedia.org/wiki/The_Tower_at_Stony_Wood"],
["2003","","Robert A. Metzger","Picoverse",""],
["2003","","Kelley Eskridge","Solitaire",""],
["2003","Nebula","Neil Gaiman","American Gods","https://en.wikipedia.org/wiki/American_Gods"],
["2003","","Michael Swanwick","Bones of the Earth","https://en.wikipedia.org/wiki/Bones_of_the_Earth"],
["2003","","David Brin","Kiln People (aka: Kil'n People)","https://en.wikipedia.org/wiki/Kiln_People"],
["2003","","China Mi‚ville","Perdido Street Station","https://en.wikipedia.org/wiki/Perdido_Street_Station"],
["2003","Hugo","Robert J. Sawyer","Hominids","https://en.wikipedia.org/wiki/The_Neanderthal_Parallax"],
["2003","","Ursula K. Le Guin","The Other Wind","https://en.wikipedia.org/wiki/The_Other_Wind"],
["2003","","China Mi‚ville","The Scar","https://en.wikipedia.org/wiki/The_Scar"],
["2003","","Kim Stanley Robinson","The Years of Rice and Salt","https://en.wikipedia.org/wiki/The_Years_of_Rice_and_Salt"],
["2004","","Kathleen Ann Goonan","Light Music",""],
["2004","","Robert Charles Wilson","Blind Lake","https://en.wikipedia.org/wiki/Blind_Lake"],
["2004","","Jack McDevitt","Chindi","https://en.wikipedia.org/wiki/Chindi_(novel)"],
["2004","","Lois McMaster Bujold","Diplomatic Immunity","https://en.wikipedia.org/wiki/Diplomatic_Immunity_(novel)"],
["2004","","Dan Simmons","Ilium","https://en.wikipedia.org/wiki/Ilium_(novel)"],
["2004","Hugo","Lois McMaster Bujold","Paladin of Souls","https://en.wikipedia.org/wiki/Paladin_of_Souls"],
["2004","","Charles Stross","Singularity Sky","https://en.wikipedia.org/wiki/Singularity_Sky"],
["2004","Nebula","Elizabeth Moon","The Speed of Dark","https://en.wikipedia.org/wiki/Speed_of_Dark"],
["2004","","Carol Emshwiller","The Mount","https://en.wikipedia.org/wiki/The_Mount_(novel)"],
["2004","","Robert J. Sawyer","Humans","https://en.wikipedia.org/wiki/The_Neanderthal_Parallax"],
["2004","","Nalo Hopkinson","The Salt Roads","https://en.wikipedia.org/wiki/The_Salt_Roads"],
["2005","","David Mitchell","Cloud Atlas","https://en.wikipedia.org/wiki/Cloud_Atlas_(novel)"],
["2005","","Cory Doctorow","Down and Out in the Magic Kingdom","https://en.wikipedia.org/wiki/Down_and_Out_in_the_Magic_Kingdom"],
["2005","","China Mi‚ville","Iron Council","https://en.wikipedia.org/wiki/Iron_Council"],
["2005","","Charles Stross","Iron Sunrise","https://en.wikipedia.org/wiki/Iron_Sunrise"],
["2005","Hugo","Susanna Clarke","Jonathan Strange & Mr Norrell","https://en.wikipedia.org/wiki/Jonathan_Strange_%26_Mr_Norrell"],
["2005","","Jack McDevitt","Omega","https://en.wikipedia.org/wiki/Omega_(novel)"],
["2005","Nebula","Lois McMaster Bujold","Paladin of Souls","https://en.wikipedia.org/wiki/Paladin_of_Souls"],
["2005","","Sean Stewart","Perfect Circle","https://en.wikipedia.org/wiki/Perfect_Circle_(novel)"],
["2005","","Ian McDonald","River of Gods","https://en.wikipedia.org/wiki/River_of_Gods"],
["2005","","Iain M. Banks","The Algebraist","https://en.wikipedia.org/wiki/The_Algebraist"],
["2005","","Gene Wolfe","The Knight","https://en.wikipedia.org/wiki/The_Knight_(Gene_Wolfe)"],
["2006","","George R. R. Martin","A Feast for Crows","https://en.wikipedia.org/wiki/A_Feast_for_Crows"],
["2006","","Charles Stross","Accelerando","https://en.wikipedia.org/wiki/Accelerando"],
["2006","","Geoff Ryman","Air","https://en.wikipedia.org/wiki/Air_(novel)"],
["2006","Nebula","Joe Haldeman","Camouflage","https://en.wikipedia.org/wiki/Camouflage_(novel)"],
["2006","","Terry Pratchett","Going Postal","https://en.wikipedia.org/wiki/Going_Postal"],
["2006","","Susanna Clarke","Jonathan Strange & Mr Norrell","https://en.wikipedia.org/wiki/Jonathan_Strange_%26_Mr_Norrell"],
["2006","","Ken MacLeod","Learning the World","https://en.wikipedia.org/wiki/Learning_the_World"],
["2006","","John Scalzi","Old Man's War","https://en.wikipedia.org/wiki/Old_Man%27s_War"],
["2006","","John C. Wright","Orphans of Chaos","https://en.wikipedia.org/wiki/Orphans_of_Chaos"],
["2006","","Jack McDevitt","Polaris","https://en.wikipedia.org/wiki/Polaris_(novel)"],
["2006","Hugo","Robert Charles Wilson","Spin","https://en.wikipedia.org/wiki/Spin_(novel)"],
["2007","","Jeffrey Ford","The Girl in the Glass",""],
["2007","","Ellen Kushner","The Privilege of the Sword",""],
["2007","","Peter Watts","Blindsight","https://en.wikipedia.org/wiki/Blindsight_(Watts_novel)"],
["2007","","Michael F. Flynn","Eifelheim","https://en.wikipedia.org/wiki/Eifelheim"],
["2007","","Jo Walton","Farthing","https://en.wikipedia.org/wiki/Farthing_(novel)"],
["2007","","Richard Bowes","From the Files of the Time Rangers","https://en.wikipedia.org/wiki/From_the_Files_of_the_Time_Rangers"],
["2007","","Charles Stross","Glasshouse","https://en.wikipedia.org/wiki/Glasshouse_(novel)"],
["2007","","Naomi Novik","His Majesty's Dragon","https://en.wikipedia.org/wiki/His_Majesty%27s_Dragon"],
["2007","Hugo","Vernor Vinge","Rainbows End","https://en.wikipedia.org/wiki/Rainbows_End"],
["2007","Nebula","Jack McDevitt","Seeker","https://en.wikipedia.org/wiki/Seeker_(novel)"],
["2007","","Wil McCarthy","To Crush the Moon","https://en.wikipedia.org/wiki/To_Crush_the_Moon"],
["2008","","Nalo Hopkinson","The New Moon's Arms",""],
["2008","","Ian McDonald","Brasyl","https://en.wikipedia.org/wiki/Brasyl"],
["2008","","Charles Stross","Halting State","https://en.wikipedia.org/wiki/Halting_State"],
["2008","","Jack McDevitt","Odyssey","https://en.wikipedia.org/wiki/Odyssey_(novel)"],
["2008","","Tobias S. Buckell","Ragamuffin","https://en.wikipedia.org/wiki/Ragamuffin_(novel)"],
["2008","","Robert J. Sawyer","Rollback","https://en.wikipedia.org/wiki/Rollback_(novel)"],
["2008","","Joe Haldeman","The Accidental Time Machine","https://en.wikipedia.org/wiki/The_Accidental_Time_Machine"],
["2008","","John Scalzi","The Last Colony","https://en.wikipedia.org/wiki/The_Last_Colony"],
["2008","Hugo,Nebula","Michael Chabon","The Yiddish Policemen's Union","https://en.wikipedia.org/wiki/The_Yiddish_Policemen%27s_Union"],
["2009","","Neal Stephenson","Anathem",""],
["2009","","Jack McDevitt","Cauldron",""],
["2009","","David J. Schwartz","Superpowers",""],
["2009","Nebula","Ursula K. Le Guin","Powers","https://en.wikipedia.org/wiki/Annals_of_the_Western_Shore"],
["2009","","Ian McDonald","Brasyl","https://en.wikipedia.org/wiki/Brasyl"],
["2009","","Cory Doctorow","Little Brother","https://en.wikipedia.org/wiki/Little_Brother_(Doctorow_novel)"],
["2009","","Terry Pratchett","Making Money","https://en.wikipedia.org/wiki/Making_Money"],
["2009","","Charles Stross","Saturn's Children","https://en.wikipedia.org/wiki/Saturn%27s_Children_(novel)"],
["2009","Hugo","Neil Gaiman","The Graveyard Book","https://en.wikipedia.org/wiki/The_Graveyard_Book"],
["2009","","John Scalzi","Zoe's Tale","https://en.wikipedia.org/wiki/Zoe%27s_Tale"],
["2010","","Christopher Barzak","The Love We Share Without Knowing",""],
["2010","","Cherie Priest","Boneshaker","https://en.wikipedia.org/wiki/Boneshaker_(novel)"],
["2010","","Cherie Priest","Boneshaker","https://en.wikipedia.org/wiki/Boneshaker_(novel)"],
["2010","","Jeff VanderMeer","Finch","https://en.wikipedia.org/wiki/Finch_(novel)"],
["2010","","Laura Anne Gilman","Flesh and Fire","https://en.wikipedia.org/wiki/Flesh_and_Fire"],
["2010","","Robert Charles Wilson","Julian Comstock: A Story of 22nd-Century America","https://en.wikipedia.org/wiki/Julian_Comstock:_A_Story_of_22nd-Century_America"],
["2010","","Catherynne M. Valente","Palimpsest","https://en.wikipedia.org/wiki/Palimpsest_(novel)"],
["2010","Hugo","China Mi‚ville","The City & the City","https://en.wikipedia.org/wiki/The_City_%26_the_City"],
["2010","","China Mi‚ville","The City & the City","https://en.wikipedia.org/wiki/The_City_%26_the_City"],
["2010","Hugo,Nebula","Paolo Bacigalupi","The Windup Girl","https://en.wikipedia.org/wiki/The_Windup_Girl"],
["2010","","Robert J. Sawyer","Wake","https://en.wikipedia.org/wiki/Wake_(Robert_J._Sawyer_novel)"],
["2011","","Jack McDevitt","Echo",""],
["2011","","Mary Robinette Kowal","Shades of Milk and Honey",""],
["2011","","Nnedi Okorafor","Who Fears Death",""],
["2011","Hugo,Nebula","Connie Willis","Blackout/All Clear","https://en.wikipedia.org/wiki/Blackout/All_Clear"],
["2011","","Lois McMaster Bujold","Cryoburn","https://en.wikipedia.org/wiki/Cryoburn"],
["2011","","Mira Grant","Feed","https://en.wikipedia.org/wiki/Feed_(Grant_novel)"],
["2011","","Ian McDonald","The Dervish House","https://en.wikipedia.org/wiki/The_Dervish_House"],
["2011","","N. K. Jemisin","The Hundred Thousand Kingdoms","https://en.wikipedia.org/wiki/The_Hundred_Thousand_Kingdoms"],
["2011","","M. K. Hobson","The Native Star","https://en.wikipedia.org/wiki/The_Native_Star"],
["2012","","Jack McDevitt","Firebird",""],
["2012","","Kameron Hurley","God's War",""],
["2012","","Genevieve Valentine","Mechanique: a Tale of the Circus Tresaulti",""],
["2012","","N. K. Jemisin","The Kingdom of Gods",""],
["2012","","George R. R. Martin","A Dance with Dragons","https://en.wikipedia.org/wiki/A_Dance_with_Dragons"],
["2012","Hugo,Nebula","Jo Walton","Among Others","https://en.wikipedia.org/wiki/Among_Others"],
["2012","","Mira Grant","Deadline","https://en.wikipedia.org/wiki/Deadline_(Grant_novel)"],
["2012","","China Mi‚ville","Embassytown","https://en.wikipedia.org/wiki/Embassytown"],
["2012","","James S. A. Corey","Leviathan Wakes","https://en.wikipedia.org/wiki/Leviathan_Wakes"],
["2013","","Mary Robinette Kowal","Glamour in Glass",""],
["2013","","Tina Connolly","Ironskin",""],
["2013","Nebula","Kim Stanley Robinson","2312","https://en.wikipedia.org/wiki/2312_(novel)"],
["2013","","Mira Grant","Blackout","https://en.wikipedia.org/wiki/Blackout_(Grant_novel)"],
["2013","","Lois McMaster Bujold","Captain Vorpatril's Alliance","https://en.wikipedia.org/wiki/Captain_Vorpatril%27s_Alliance"],
["2013","Hugo","John Scalzi","Redshirts","https://en.wikipedia.org/wiki/Redshirts_(novel)"],
["2013","","Caitl¡n R. Kiernan","The Drowning Girl","https://en.wikipedia.org/wiki/The_Drowning_Girl"],
["2013","","N. K. Jemisin","The Killing Moon","https://en.wikipedia.org/wiki/The_Killing_Moon_(book)"],
["2013","","Saladin Ahmed","Throne of the Crescent Moon","https://en.wikipedia.org/wiki/Throne_of_the_Crescent_Moon"],
["2014","","Sofia Samatar","A Stranger in Olondria",""],
["2014","","Charles E. Gannon","Fire with Fire",""],
["2014","","Nicola Griffith","Hild",""],
["2014","","Linda Nagata","The Red: First Light",""],
["2014","","Robert Jordan & Brandon Sanderson","The Wheel of Time",""],
["2014","","Larry Correia","Warbound",""],
["2014","","Karen Joy Fowler","We Are All Completely Beside Ourselves",""],
["2014","Hugo,Nebula","Ann Leckie","Ancillary Justice","https://en.wikipedia.org/wiki/Ancillary_Justice"],
["2014","","Charles Stross","Neptune's Brood","https://en.wikipedia.org/wiki/Neptune%27s_Brood"],
["2014","","Mira Grant","Parasite","https://en.wikipedia.org/wiki/Parasite_(Grant_novel)"],
["2014","","Helene Wecker","The Golem and the Jinni","https://en.wikipedia.org/wiki/The_Golem_and_the_Jinni"],
["2014","","Neil Gaiman","The Ocean at the End of the Lane","https://en.wikipedia.org/wiki/The_Ocean_at_the_End_of_the_Lane"],
["2015","","Ann Leckie","Ancillary Sword","https://en.wikipedia.org/wiki/Ancillary_Sword"],
["2015","Nebula","Jeff VanderMeer","Annihilation","https://en.wikipedia.org/wiki/Annihilation_(VanderMeer_novel)"],
["2015","","Jack McDevitt","Coming Home","https://en.wikipedia.org/wiki/Coming_Home_(Jack_McDevitt)"],
["2015","","Jim Butcher","Skin Game","https://en.wikipedia.org/wiki/Skin_Game_(The_Dresden_Files)"],
["2015","","Katherine Addison","The Goblin Emperor","https://en.wikipedia.org/wiki/The_Goblin_Emperor"],
["2015","","Kevin J. Anderson","The Dark Between the Stars","https://en.wikipedia.org/wiki/The_Saga_of_Shadows"],
["2015","","Cixin Liu","The Three-Body Problem","https://en.wikipedia.org/wiki/The_Three-Body_Problem"],
["2015","","Charles E. Gannon","Trial by Fire",""]

]

nominee_list.each do |year, award, author, title, link|
  Nominee.create( year: year, award: award, author: author, title: title, link: link )
end